fix: add case-insensitive filtering in all searchs
diego3g/umbriel pull request #100
Opened 2021-08-05 02:03 UTC by brunooomelo

2021-08-09 13:27 UTC, diego3g commented on src/modules/broadcasting/repositories/in-memory/InMemoryMessagesRepository.ts
> +        message.subject.value.includes(query.toLowerCase())
Shoudn't we also lowercase the `message.subject.value` as well before comparing to query? As we are only lowercasing the query, if the subject contain capitalized chars, it won't be found.

2021-08-09 13:30 UTC, diego3g requested changes

2021-08-09 13:30 UTC, diego3g commented on src/modules/broadcasting/useCases/SearchMessages/SearchMessagesController.spec.ts
> +  it('should be able to search messages', async () => {
I think the test name here is duplicated.

2021-08-09 13:30 UTC, diego3g commented on src/modules/subscriptions/useCases/SearchContacts/SearchContacts.spec.ts
> +  it('should be able to search through contacts', async () => {
Again, the test name is duplicated.

2021-08-12 12:00 UTC, diego3g commented
@brunooomelo will u be able to fix this?

2021-08-13 02:07 UTC, brunooomelo commented
Sure.

2021-08-13 14:55 UTC, diego3g approved these changes

2021-08-13 17:08 UTC, merged